import turtle
win=turtle.Screen()
win.bgcolor("grey")
name=turtle.Turtle()
name.pensize(2)
name.up ( )
name.goto (0,35)
name.down ( )
name.color ('red')
name.circle (20)
name.up ( )
name.goto (0,-20)
name.down ( )
name.color ('blue')
name.circle (20)
name.up ( )
name.goto (0,-75)
name.down ( )
name.color ('green')
name.circle (20)
win.exitonclick()
